development:
  adapter: postgresql
  encoding: unicode
  database: sign_in_with_twitter_development
  pool: 5
  username: jkhatiblou@gmail.com
  password: h1pch3K3rb0ard_

test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
