#grey
development:
  adapter: postgresql
  database: d68rtln15e8hbr
  host: ec2-54-243-229-57.compute-1.amazonaws.com
  user: sembfxvxuvmimc
  password: jlZB7lwS3_P9g1fiH-0qjDecvY
  port: 5432


test:
  adapter: postgresql
  database: sign_in_with_twitter_test
  host: localhost
